### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DJ45X** [DKRCommands/DKRCommands#3]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### ✏ Description

I have been trying to update an existing bot to Discord.js v14 for a while now. But I keep running into the same issue across 4 different bots that use DKRCommands; the event handling just does not work at all. I have the correct folder structure and naming scheme. I have an discord interactionCreate event listener for handling button presses and they never work. My code works perfectly fine if I put that listener in the index.js though. I would very much like to keep it out of the index.js to keep my work space clean and organized. 

### 👟 Reproduction steps

I'm not so sure there are any steps to take. I can instead paste my code in a srcshare here and see what you think. [srcshare link](https://srcshare.io/63a31dbc906d8373f44b2daa).

### 🔢 DKRCommands version

1.0.0-beta.4

### 💻 Operating system

Microsoft Windows

### 🔢 Node.js version

16.15.0

### 👀 Expected behavior

The `client.on(interactionCreate)` event listener should work in its own file without needing to be in the index.js.

### 😥 Actual behavior

Bot comes online, console shows commands load, and the event "loads". But When I interact with the button the listener handles, it fails. No errors or anything. Bot doesn't crash. Just nothing from the event listener. 

Everything above and outside of the `module.exports` runs. But anything inside the `module.exports` does not run at all. 

### 📝 Relevant log output

```shell
No relevant log info to provide.
```

**Comment by DJ45X** [comment]
I have a bot that has entered its first stage of production. In the coming months, i will definitely need event handling working as there will be a number of functions needed. I'm the lead bot developer for a rocket league community and Bonnie is our bot that will handle things like player cards, database on player info, and pulling info from our scrim bot, Clyde. While it may not be critical right now as we only just launched the bot, we will need this ready before our second season begins middle of next year.

**Comment by karelkryda** [comment]
Hello,
this is very strange, because I tested the behavior and all my events in the folder worked without problems.
Could I ask you if you could test the functionality of the `messageCreate` sample event from the documentation? I tested this demonstration event and it worked without any problems. 

Would you tell me if your code is running as TypeScript or JavaScript? I tested the behavior of events in a separate folder when using TypeScript code and I wonder if I wrote the sample code for JavaScript correctly.

**Comment by karelkryda** [comment]
Just to make sure. Do I understand correctly that an event in the `index.js` file works, but not in the events folder?

**Comment by DJ45X** [comment]
> Just to make sure. Do I understand correctly that an event in the `index.js` file works, but not in the events folder?

That is correct. I am using purely javascript. No typescript (i have a hate/hate relationship with it lol).  

I did try the example given in the docs as well and have the same issue. Events just don't run at all despite following documentation to the letter.

Thank you for the quick reply!

**Comment by karelkryda** [comment]
Okay, that means either I made a mistake in the documentation for the JavaScript code, or it will be some other problem. 

Unfortunately, I'm not feeling well at the moment and I'm lying in bed, so I can't immediately figure out where the problem is. Could you please give me a few days? Alternatively, I will try to find out something from the phone, but I do not promise anything. 

Thank you for your understanding

**Comment by DJ45X** [comment]
No worries my friend! I can still continue development on my side as the listeners work in the index.js for now. Thank you so much for looking into this. Take the time you need to get well! Warm wishes and happy holidays! I humbly await word from you again!

**Comment by karelkryda** [comment]
Hello, 
I have just tested the `messageCreate` and `interactionCreate` events in JavaScript according to the example in the DKRCommands documentation and they work without problems. I used the following intents for testing:
 - GatewayIntentBits.Guilds
 - GatewayIntentBits.MessageContent
 - GatewayIntentBits.GuildMessageReactions
 - GatewayIntentBits.DirectMessages
 - GatewayIntentBits.GuildMessages

Testing on my test server without any problems.

Could I ask you to show me the structure of your events directory, including verifying the correctness of the `eventsDir` parameter in the DKRCommands constructor?

Thank you

**Comment by DJ45X** [comment]
Folder Structure
![image](https://user-images.githubusercontent.com/93067044/209674509-880d8803-46d4-4ca0-9dfd-d912353f6fbe.png)

You'll see the `eventsDir` is commented out. This is to just disable it while it doesn't work. 

`client.on(Events.ClientReady, () => {
    new DKRCommands(client, {
        commandsDir: join(__dirname, "Commands"),
        // eventsDir: join(__dirname, "Events"),
        testServers: ["a-discord-id"],
    });
    // Make a switch case to define a message for each day of the week
    client.user.setActivity('RL until Clyde arrives', { type: ActivityType.Playing });
});
`

Currently using these intents:
- GatewayIntentBits.Guilds
- GatewayIntentBits.GuildMembers
- GatewayIntentBits.GuildMessageReactions
- GatewayIntentBits.GuildScheduledEvents
- GatewayIntentBits.GuildWebhooks

The `ic1.js` event:

https://srcshare.io/63aaf7f9b51b9d7ca838c643

**Comment by karelkryda** [comment]
I see where the problem probably is. Lemme fix your event file. I'll send you correct version soon.

**Comment by karelkryda** [comment]
I am attaching a working (hopefully) [event file](https://srcshare.io/63ab0f3c844bc53611e9130b).

The problem was that the event file is already an event, but you were creating a de facto event listener again in the event file. Another thing is that the first parameter of the event is always `instance`, i.e. an instance of DKRCommands. But I forgot to mention this in the [documentation](https://karel-kryda.gitbook.io/dkrcommands/useful-information/discord.js-events) and I apologize for that, I will fix it.

I will ask you to test if this file is already working.
Thank you

_EDIT: added information about `instance` parameter to documentation_

**Comment by DJ45X** [comment]
This worked like a charm! I completely didn't think about trying to run the event listener without the `client.on` within it. Thank you so much!
